<?php

namespace GameBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQuestionsNotValid() {
        return $this->createQueryBuilder('q')
            ->leftJoin('q.subject', 's')
            ->leftJoin('q.userCount', 'u')
            ->addSelect('s')
            ->addSelect('u')
            ->where('q.isValid = :isValid')
            ->setParameter('isValid', false)
            ->getQuery()
            ->getArrayResult()
		;
    }
}
