<?php

namespace GameBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQuestionsByValidity($validity) {
        return $this->createQueryBuilder('q')
            ->leftJoin('q.topic', 't')
            ->leftJoin('q.userCount', 'u')
            ->leftJoin('t.subject', 'su')
            ->leftJoin('q.schoolClass', 'sc')
            ->addSelect('t')
            ->addSelect('u')
            ->addSelect('su')
            ->addSelect('sc')
            ->where('q.isValid = :isValid')
            ->setParameter('isValid', $validity)
            ->orderBy('q.schoolClass', 'ASC')
            ->getQuery()
            ->getArrayResult()
		;
    }

    public function findBySubjectAndBySchoolClass($subject, $schoolClass) {
        return $this->createQueryBuilder('q')
            ->leftJoin('q.topic', 't')
            ->leftJoin('t.subject', 'su')
            ->leftJoin('q.schoolClass', 'sc')
            ->where('t.subject = :subject')
            ->andWhere('q.schoolClass = :schoolClass')
            ->andWhere('q.isValid = :isValid')            
            ->setParameter('subject', $subject)
            ->setParameter('schoolClass', $schoolClass)
            ->setParameter('isValid', true)
            ->getQuery()
            ->getResult()
		;
    }

    public function getRandomQuestion($idQuestionList) {
        $randomId = array_rand($idQuestionList, 1);
        
        return $this->createQueryBuilder('q')
            ->leftJoin('q.topic', 't')
            ->leftJoin('t.subject', 'su')
            ->leftJoin('q.answers', 'a')
            ->leftJoin('q.schoolClass', 'sc')
            ->addSelect('t')
            ->addSelect('su')
            ->addSelect('a')
            ->addSelect('sc')
            ->where('q.id = :randomId')
            ->setParameter('randomId', $idQuestionList[$randomId])
            ->getQuery()
            ->getArrayResult()[0]
        ;
    }

    public function findMyQuestions($userCount, $validity) {
        return $this->createQueryBuilder('q')
            ->leftJoin('q.topic', 't')
            ->leftJoin('q.userCount', 'u')
            ->leftJoin('q.schoolClass', 's')
            ->addSelect('t')
            ->addSelect('u')
            ->addSelect('s')
            ->where('q.userCount = :userCount')
            ->andWhere('q.isValid = :isValid')
            ->setParameter('userCount', $userCount)
            ->setParameter('isValid', $validity)
            ->getQuery()
            ->getResult()
		;
    }

    public function count($subjectId, $schoolLevelId) {
		return $this->createQueryBuilder('q')
		    ->select('COUNT(q)')
            ->leftJoin('q.schoolClass', 'sc')
            ->leftJoin('q.topic', 't')
            ->leftJoin('t.subject', 'su')
		    ->where('su.id = :subjectId')
            ->andWhere('sc.id = :schoolLevelId')
            ->andWhere('q.isValid = :isValid')
            ->setParameter('subjectId', $subjectId)
            ->setParameter('schoolLevelId', $schoolLevelId)
            ->setParameter('isValid', true)
            ->getQuery()
            ->execute()
		;
	}

}
