<?php

namespace GameBundle\Repository;

use Doctrine\ORM\Query\Expr\Join;
use GameBundle\Entity\Question;
use GameBundle\Entity\Topic;
use GameBundle\Entity\Subject;

/**
* SchoolClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolClassRepository extends \Doctrine\ORM\EntityRepository
{
	public function orderBy() {
		return $this->createQueryBuilder('s')
		->orderBy('s.id', 'ASC')
		;
	}

	public function findAll() {
		return $this->findBy(array(), array('id' => 'ASC'));
	}

	public function countBySubject($id) {
		return $this->createQueryBuilder('sc')
		->select('COUNT(distinct sc)')
            ->leftJoin('sc.questions', 'q')
            ->leftJoin('q.topic', 't')
            ->leftJoin('t.subject', 'su')
		->where('su.id = :id')
            ->andWhere('q.isValid = :isValid')
            ->setParameter('id', $id)
            ->setParameter('isValid', true)
            ->getQuery()
            ->execute()
		;
	}

	public function getBySubject($id) {
		return $this->createQueryBuilder('sc')
		->select('distinct sc')
            ->leftJoin('sc.questions', 'q')
            ->leftJoin('q.topic', 't')
            ->leftJoin('t.subject', 'su')
		->where('su.id = :id')
            ->andWhere('q.isValid = :isValid')
            ->setParameter('id', $id)
            ->setParameter('isValid', true)
            ->orderBy('sc.id', 'ASC')
            ->getQuery()
            ->execute()
		;
	}
}
