<?php

namespace GameBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;
use GameBundle\Entity\Topic;
use GameBundle\Entity\Question;

/**
 * SubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends EntityRepository
{
    public function findAll() {
        return $this->createQueryBuilder('su')
            ->join(Topic::class, 't', Join::WITH, 'su = t.subject')
            ->join(Question::class, 'q', Join::WITH, 't = q.topic')
            ->where('q.isValid = :isValid')
            ->setParameter('isValid', true)
            ->having('COUNT(q) >= :counter')
            ->setParameter('counter', 2)
            ->groupBy('su')
            ->orderBy('su.id', 'ASC')
            ->getQuery()
            ->getResult()
		;
    }
}
