<?php

namespace GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectRepository extends EntityRepository
{
    public function findAll() {
        return $this->findBy(array(), array('id' => 'ASC'));
    }
}
