<?php

namespace GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends EntityRepository
{
      public function getTopicsFromSubject($idSubject) {
		return $this->createQueryBuilder('t')
            ->leftJoin('t.subject', 's')
            ->where('s.id = :id')
            ->setParameter('id', $idSubject)
            ->getQuery()
            ->getArrayResult()
		;
      }    
}
