<?php

namespace GameBundle\Repository;

/**
 * UserCountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCountRepository extends \Doctrine\ORM\EntityRepository
{
}
