add_question:
    path:     /add
    defaults: { _controller: GameBundle:Default:addQuestion }

combobox:
    path: /combobox
    defaults: { _controller: GameBundle:Admin:combobox }
    requirements: 
        _method: POST

valid_answers:
    path: /valid
    defaults: { _controller: GameBundle:Admin:validAnswers }
    requirements: 
        _method: POST

remove_answer:
    path: /remove
    defaults: { _controller: GameBundle:Admin:removeAnswer }
    requirements: 
        _method: POST