
combobox:
    path: /combobox
    defaults: { _controller: GameBundle:Admin:combobox }
    requirements: 
        _method: POST

remove_answer:
    path: /remove/{id}
    defaults: { _controller: GameBundle:Admin:removeAnswer }
    requirements: 
        _method: DELETE

validate_question:
    path: /validate/{id}
    defaults:
        _controller: GameBundle:Admin:validateQuestion
        id: 1            
    requirements:
        id: \d+

suggest_question:
   path:    /suggest
   defaults: { _controller: GameBundle:HomeFamily:suggestQuestion }

add_question:
    path:    /add
    defaults: { _controller: GameBundle:Admin:addQuestion }

moderate_question:
    path:    /moderate
    defaults: { _controller: GameBundle:Admin:moderateQuestion }

question_delete:
    path:   /delete/{id}
    defaults: { _controller: GameBundle:Admin:deleteQuestion }
    requirements:
        id: \d+

options_question:
    path:    /options
    defaults: { _controller: GameBundle:Admin:optionsQuestion }

play:
    path:    /play
    defaults: { _controller: GameBundle:Game:play }

topic_delete:
    path:   topic/delete/{id}
    defaults: { _controller: GameBundle:Admin:deleteTopic }
    requirements:
        id: \d+

subject_delete:
    path:   subject/delete/{id}
    defaults: { _controller: GameBundle:Admin:deleteSubject }
    requirements:
        id: \d+