add_question:
    path:     /add
    defaults: { _controller: GameBundle:Default:addQuestions }

combobox:
    path: /combobox
    defaults: { _controller: GameBundle:Admin:combobox }
    requirements: 
        _method: POST
