game_homepage:
    path:     /
    defaults: { _controller: GameBundle:Default:index }

game_signup:
    path:     /signup
    defaults: { _controller: GameBundle:Session:signup }

game_login:
    path:     /login
    defaults: { _controller: GameBundle:Session:login }

login_check:
    path: /login_check

logout:
    path: /logout





gamer_view:
    path:     /{id}
    defaults: { _controller: GameBundle:Default:view }
    requirements:
        id: \d+
        
gamer_add:
    path:      /add
    defaults:
        _controller: GameBundle:Default:add

gamer_edit:
    path:      /edit/{id}
    defaults:
        _controller: GameBundle:Default:edit
    requirements:
        id: \d+

gamer_delete:
    path:      /delete/{id}
    defaults:
        _controller: GameBundle:Default:delete
    requirements:
        id: \d+