
combobox:
    path: /combobox
    defaults: { _controller: GameBundle:Admin:combobox }
    requirements: 
        _method: POST

remove_answer:
    path: /remove/{id}
    defaults: { _controller: GameBundle:Admin:removeAnswer }
    requirements: 
        _method: DELETE

validate_question:
    path: /validate/{id}
    defaults:
        _controller: GameBundle:Admin:validateQuestion
        id: 1            
    requirements:
        id: \d+

suggest_question:
   path:    /suggest
   defaults: { _controller: GameBundle:HomeFamily:suggestQuestion }

notifications:
   path:    /notifications
   defaults: { _controller: GameBundle:HomeFamily:getNotifications }

add_question:
    path:    /add
    defaults: { _controller: GameBundle:Admin:addQuestion }

moderate_question:
    path:    /moderate
    defaults: { _controller: GameBundle:Admin:moderateQuestion }

question_delete:
    path:   /delete/{id}
    defaults: { _controller: GameBundle:Admin:deleteQuestion }
    requirements:
        id: \d+

options_question:
    path:    /options
    defaults: { _controller: GameBundle:Admin:optionsQuestion }

topic_delete:
    path:   topic/delete/{id}
    defaults: { _controller: GameBundle:Admin:deleteTopic }
    requirements:
        id: \d+

subject_delete:
    path:   subject/delete/{id}
    defaults: { _controller: GameBundle:Admin:deleteSubject }
    requirements:
        id: \d+

play:
    path:    /play
    defaults: { _controller: GameBundle:Game:play }
    requirements:
        id: \d+

get_random_question:
    path: /random/{subjectId}/{gamerId}
    defaults: { _controller: GameBundle:Game:getRandomQuestion }
    requirements: 
        _method: GET
        subjectId: \d+
        gamerId: \d+
        
valid_answer:
    path: /valid/answer/{answerId}/{gamerId}/{dice}/{score}/{bonus}
    defaults: { _controller: GameBundle:Game:validAnswer }
    requirements: 
        _method: POST
        answerId: \d+
        gamerId: \d+
        dice: \d+
        score: \d+
        bonus: \d+

change_stats:
    path: /bestscore/{finalScore}/{bestScore}/{gamerId}/{gameWonNb}/{cumulScore}/{level}/{index}
    defaults: { _controller: GameBundle:Game:changeStats }
    requirements: 
        _method: POST
        finalScore: \d+
        bestScore: \d+
        gamerId: \d+
        gameWonNb: \d+
        cumulScore: \d+
        level: \d+
        index: \d+