imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

        # grouped:
        #     type:               group
        #     members:            [nested, swift]
        # swift:
        #     type:               swift_mailer
        #     from_email:         FQN@foo.com
        #     to_email:           webmaster@company.com
        #     subject:            "OOps"
        #     level:              debug
        # login:
        #     type:               stream
        #     path:               "%kernel.logs_dir%/auth.log"
        #     level:              info
        #     channels:           security
        