question:
    resource: "@GameBundle/Resources/config/routing.yml"
    prefix:   /question    

# game:
#     resource: "@GameBundle/Resources/config/routing.yml"
#     prefix:   /game

home:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

signup:
    path:     /signup
    defaults: { _controller: UserBundle:Session:signup }

login:
    path:     /login
    defaults: { _controller: UserBundle:Session:login }
