# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        UserBundle\Entity\UserCount:
            algorithm: bcrypt
    
    role_hierarchy:
        ROLE_ENSEIGNANT: ROLE_USER
        ROLE_ADMIN: [ROLE_ENSEIGNANT, ROLE_USER]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:      
        my_db_provider:
            entity:
                class: UserBundle:UserCount
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:      ^/
            anonymous:    true
            provider:     my_db_provider
            form_login:
                login_path: login
                check_path: login_check
                always_use_default_target_path: false
                default_target_path: /
                target_path_parameter: _target_path
                use_referer: false
                csrf_token_generator: security.csrf.token_manager

            logout:
                path:       logout
                target:     /game
            remember_me:
                secret:     '%secret%'
    
    access_control:
     - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
     - { path: ^/admin, roles: ROLE_ADMIN}


            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

