# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    
    update.gamer:
        class: GameBundle\Controller\StatsGamer

    stats.question:
        class: GameBundle\Controller\StatsQuestion
        arguments: ['@doctrine.orm.entity_manager']
