<?php

namespace UserBundle\Repository;

/**
 * GamerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGamersByUserCount($userCount) {
        return $this->createQueryBuilder('g')
            ->leftJoin('g.schoolClass', 's')
            ->addSelect('s')
            ->where('g.userCount = :userCount')
            ->setParameter('userCount', $userCount)
            ->getQuery()
            ->getResult()
		;
    }
}