<?php

namespace UserBundle\Repository;

/**
 * UserCountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCountRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserByRole($role) {
        return $this->createQueryBuilder('u')
            ->where('u.roles LIKE :role')
            ->setParameter('role', '%' . $role . '%')
            ->getQuery()
            ->getResult()
		;
    }

}
