homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

login_check:
    path:     /login_check

logout:
    path:     /logout

select_gamers:
    path:   /select
    defaults: { _controller: GameBundle:HomeFamily:select }    

check_scores:
   path:    /scores
   defaults: { _controller: GameBundle:HomeFamily:checkScores }

admin_gamers:
   path:    /gamers
   defaults: { _controller: UserBundle:Gamer:manager }

admin_users:
   path:    /administration
   defaults: { _controller: UserBundle:Default:manageUsers }

user_edit:
    path:   /edit/{id}
    defaults: { _controller: UserBundle:Default:editUser }
    requirements:
        id: \d+

user_delete:
    path:   /delete/{id}
    defaults: { _controller: UserBundle:Default:deleteUser }
    requirements:
        id: \d+

settings_user:
    path:   /settings/{id}
    defaults: { _controller: UserBundle:Session:settings }
    requirements:
        id: \d+

add_gamer:
    path:   /add
    defaults: { _controller: UserBundle:Gamer:add }